apiVersion: batch/v1
kind: Job
metadata:
  name: scot4-search-init
spec:
  template:
    spec:
      containers:
      - name: scot4-search-init
        imagePullPolicy: "Always"
        image: "{{ .Values.scot4.api.utilRepository }}:{{ .Values.scot4.api.utilTag }}"
        command: ["python", "./tests/utils/index_search.py"]
        envFrom:
        - configMapRef:
            name: scot4-api-env-config
        - secretRef:
            name: scot4-env-secrets
      restartPolicy: Never
      {{- if .Values.scot4.common.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.scot4.common.imagePullSecret }}
      {{- end }}
