apiVersion: v1
kind: Service
metadata:
  name: scot4-flair-service
spec:
  ports:
  - port: {{ .Values.scot4.flair.containerPort }}
  selector:
    app: scot4-flair
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scot4-flair
spec:
  selector:
    matchLabels:
      app: scot4-flair
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scot4-flair
        {{- if eq .Values.scot4.force_pod_redeploy "true" }}
        date: "{{ now | unixEpoch }}"
        {{- end }}
    spec:
      {{- if eq .Values.scot4.clean_flair_install "true" }}
      initContainers:
      - name: scot4-flair-init
        imagePullPolicy: {{ .Values.scot4.flair.imagePullPolicy }}
        image: "{{ .Values.scot4.flair.repository }}:{{ .Values.scot4.flair.tag }}"
        command: ["/bin/bash", "-c", "./setup.pl --wipedb"]
        envFrom:
        - secretRef:
            name: scot4-flair-secrets
        - configMapRef:
            name: scot4-flair-env-config
        volumeMounts:
        - name: scot4-flair-opt-storage
          mountPath: /opt/flair/var
      {{- end }}
      containers:
      - image: "{{ .Values.scot4.flair.repository }}:{{ .Values.scot4.flair.tag }}"
        imagePullPolicy: {{ .Values.scot4.flair.imagePullPolicy }}
        name: scot4-flair-webserver
        envFrom:
        - secretRef:
            name: scot4-flair-secrets
        - configMapRef:
            name: scot4-flair-env-config
        command: ["/opt/perl/bin/hypnotoad", "-f", "/opt/flair/script/Flair"]
        ports:
        - containerPort: {{ .Values.scot4.flair.containerPort }}
          name: scot4-flair
        volumeMounts:
        - name: scot4-flair-opt-storage
          mountPath: /opt/flair/var
          readOnly: false
      - image: "{{ .Values.scot4.flair.repository }}:{{ .Values.scot4.flair.tag }}"
        imagePullPolicy: {{ .Values.scot4.flair.imagePullPolicy }}
        name: scot4-flair-minion
        envFrom:
        - secretRef:
            name: scot4-flair-secrets
        - configMapRef:
            name: scot4-flair-env-config
        command: ["/opt/flair/script/Flair", "minion", "worker", "-m", "production", "-j", "{{ .Values.scot4.flair.numMinionWorkers }}"]
        volumeMounts:
        - name: scot4-flair-opt-storage
          mountPath: /opt/flair/var
          readOnly: false
      {{- if .Values.scot4.common.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.scot4.common.imagePullSecret }}
      {{- end }}
      volumes:
      - name: scot4-flair-opt-storage
        persistentVolumeClaim:
          claimName: scot4-flair-opt-pv-claim
      securityContext:
        runAsUser: 7777
        runAsGroup: 7777
        fsGroup: 7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scot4-flair-env-config
data:
  NO_PROXY: "{{ .Values.scot4.common.noProxy }}"
  S4FLAIR_VERSION: "{{ .Values.scot4.flair.version }}"
  S4FLAIR_MODE: "{{ .Values.scot4.flair.mode }}"
  S4FLAIR_LOG_LEVEL: "{{ .Values.scot4.flair.log_level }}"
  S4FLAIR_LOG_DIR: "{{ .Values.scot4.flair.log_dir }}"
  S4FLAIR_LOG_FILE: "{{ .Values.scot4.flair.log_file }}"
  S4FLAIR_MOJO_LISTEN: "{{ .Values.scot4.flair.mojo_listen }}"
  S4FLAIR_MOJO_WORKERS: "{{ .Values.scot4.flair.mojo_workers }}"
  S4FLAIR_DEFAULT_EXP_TIME: "{{ .Values.scot4.flair.default_exp_time }}"
  S4FLAIR_ADMIN_USER: "{{ .Values.scot4.flair.admin_user }}"
  S4FLAIR_ADMIN_GECOS: "{{ .Values.scot4.flair.admin_gecos }}"
  S4FLAIR_HOME_DIR: "{{ .Values.scot4.flair.home_dir }}"
  S4FLAIR_FLAIR_USER: "{{ .Values.scot4.flair.flair_user }}"
  S4FLAIR_FLAIR_GROUP: "{{ .Values.scot4.flair.flair_group }}"
  S4FLAIR_DB_URI: "{{ .Values.scot4.flair.db_uri }}"
  S4FLAIR_DB_MIGRATION: "{{ .Values.scot4.flair.db_migration }}"
  S4FLAIR_DB_FILE: "{{ .Values.scot4.flair.db_file }}"
  S4FLAIR_CORE_REGEXES: "{{ .Values.scot4.flair.core_regexes }}"
  S4FLAIR_UDEF_REGEXES: "{{ .Values.scot4.flair.udef_regexes }}"
  S4FLAIR_SCOT_API_INSECURE_SSL: "{{ .Values.scot4.flair.scot_api_insecure_ssl }}"
  S4FLAIR_SCOT_API_URI_ROOT: "{{ .Values.scot4.flair.scot_api_uri_root }}"
  MOJO_REVERSE_PROXY: "{{ .Values.scot4.flair.mojoReverseProxy }}"
  S4FLAIR_SCOT_EXTERNAL_HOSTNAME: "{{ .Values.scot4.frontend.externalHostName }}"
