apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scot4-flair-opt-pv-claim
  annotations:
    volumeType: local
    helm.sh/resource-policy: "keep"
spec:
  storageClassName: {{ .Values.scot4.flair.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.scot4.flair.storageCapacity }}
