apiVersion: v1
kind: Secret
metadata:
  name: scot4-inbox-s3-backup-secrets
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: <access key id for s3 account>
  AWS_SECRET_ACCESS_KEY: <secret access key for s3 account>
